### ISSUE TITLE
Missing analysis level command line argument

### ISSUE THREAD

**Issue by chrisgorgo** [nih-fmrif/afni_proc_BIDS_app#1]
Analysis level (third positional argument) is compulsory for all BIDS Apps even if they implement only one. In such case `participant` level should be used. More info at http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005209#sec013

**Comment by Shotgunosine** [comment]
Thanks for taking a look. I’ve added the parameter back in.
